global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - 'prometheus-metrics:9090'
  - job_name: go-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - go-service:8000